<Project>

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>preview</LangVersion>
    <SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
    <NuGetAudit>false</NuGetAudit>
    <DefineConstants>$(DefineConstants)$(FeatureFlags.Replace("#",";"))</DefineConstants>
  </PropertyGroup>

  <PropertyGroup>
    <Version>3.1.5</Version>
    <Author>Kira-NT</Author>
    <ReleaseYear>2023</ReleaseYear>
    <PackageTags>avalonia avaloniaui hot-reload dynamic hot reload xaml axaml ui development tools net netstandard</PackageTags>
  </PropertyGroup>

  <PropertyGroup>
    <AvaloniaVersion>11.0.0</AvaloniaVersion>
    <FodyVersion>6.9.2</FodyVersion>
  </PropertyGroup>

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <Authors Condition="'$(Authors)' == ''">$(Author)</Authors>
    <Company Condition="'$(Company)' == ''">$(Author)</Company>
    <Copyright Condition="'$(Copyright)' == '' And '$([System.DateTime]::Now.Year)' != '$(ReleaseYear)'">Copyright © $(ReleaseYear)-$([System.DateTime]::Now.Year) $(Authors)</Copyright>
    <Copyright Condition="'$(Copyright)' == ''">Copyright © $(ReleaseYear) $(Authors)</Copyright>
    <ProjectName Condition="'$(ProjectName)' == ''">$([System.IO.Path]::GetFileNameWithoutExtension('$([System.IO.Directory]::GetFiles(`$(MSBuildThisFileDirectory)`, `*.sln?`)[0])'))</ProjectName>
    <RepositoryUrl Condition="'$(RepositoryUrl)' == ''">https://github.com/$(Author)/$(ProjectName)</RepositoryUrl>
    <RepositoryType Condition="'$(RepositoryType)' == ''">git</RepositoryType>
    <PackageProjectUrl Condition="'$(PackageProjectUrl)' == ''">$(RepositoryUrl)</PackageProjectUrl>
  </PropertyGroup>

</Project>
